# Generated by Django 3.2.9 on 2021-11-13 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000, verbose_name='Наименвоание')),
                ('square', models.FloatField(max_length=0.0, verbose_name='Площадь')),
            ],
        ),
        migrations.CreateModel(
            name='TypeFlower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('weight_per_thousand', models.FloatField(default=0.0, verbose_name='Вес на 1000 шт.')),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diameter', models.FloatField(default=0.0, verbose_name='Диаметр')),
                ('weihgt', models.FloatField(default=0.0, verbose_name='Вес')),
                ('photo', models.FileField(upload_to='flowers/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='core.place', verbose_name='Местоположение')),
                ('type_flower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flowers', to='core.typeflower', verbose_name='Тип растения')),
            ],
        ),
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(default=0, verbose_name='Номер протокола')),
                ('gps_longitude', models.FloatField(verbose_name='Долгота')),
                ('gps_latitude', models.FloatField(verbose_name='Широта')),
                ('date', models.DateField(verbose_name='Дата')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audits', to='core.place', verbose_name='Местоположение')),
            ],
        ),
    ]
