# Generated by Django 3.2.9 on 2021-11-13 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inn', models.CharField(max_length=20, verbose_name='ИНН')),
                ('short_name', models.CharField(max_length=200, verbose_name='Короткое наименование')),
            ],
        ),
    ]
