# Generated by Django 3.2.9 on 2021-11-13 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_org_place_organiztion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='inn',
        ),
    ]
