# Generated by Django 3.2.9 on 2021-11-13 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_organization_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='inn',
            field=models.CharField(default='', max_length=20, verbose_name='ИНН'),
            preserve_default=False,
        ),
    ]
