# Generated by Django 3.2.9 on 2021-11-14 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_organization_inn'),
    ]

    operations = [
        migrations.AddField(
            model_name='flower',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Количество семян'),
        ),
    ]
